services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.development
    command: npm run start
    volumes:
      - ./:/app
    ports:
      - "8787:8080"
    depends_on:
      - mysql
  mysql:
    image: mariadb:10.5.8
    container_name: mysql_vi
    ports:
      - 3309:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: vietnamese
      MYSQL_ROOT_PASSWORD: password